### ISSUE TITLE
Modelling mithril/stream

### ISSUE THREAD

**Issue by yawaramin** [kristianmandrup/bs-mithril-stream#1]
After taking a look at the docs ( https://mithril.js.org/stream.html#stream ), I believe Mithril streams are implemented as essentially callbacks. E.g. in https://mithril.js.org/stream.html#combining-streams there's an example:

```javascript
var a = stream(5)
var b = stream(7)

var added = stream.combine(function(a, b) {
    return a() + b()
}, [a, b])

console.log(added()) // logs 12
```

According to the docs for `combine`, the `a` and `b` that get passed into the combiner function are themselves stream values. Since they get called as functions, therefore they must be functions. So based on that, I came up with the following sample set of bindings to give you an idea of the approach I would take:

```reason
/* Mithril_Stream.re */

/** Need to uncurry to prevent generating JS like x(0)
    See https://bucklescript.github.io/docs/en/function#curry-uncurry */
type t('a) = (. unit) => 'a;

/* See
   https://bucklescript.github.io/docs/en/import-export#import-a-default-value
   Test: let s = make(1); */
[@bs.module] external make: 'a => t('a) = "mithril/stream";

/* See https://bucklescript.github.io/docs/en/common-data-types#tuple
   Test:
   let s1 = make(1);
   let s2 = make(2);
   let s3 = combine2((. s1, s2) => s1(. ) + s2(. ), (s1, s2)); */
[@bs.module "mithril/stream"] external combine2: (
  (. t('a1), t('a2)) => 'b,
  (t('a1), t('a2)),
) => t('b) = "combine";

[@bs.module "mithril/stream"] external combine3: (
  (. t('a1), t('a2), t('a3)) => 'b,
  (t('a1), t('a2), t('a3)),
) => t('b) = "combine";

[@bs.module "mithril/stream"] external combine4: (
  (. t('a1), t('a2), t('a3), t('a4)) => 'b,
  (t('a1), t('a2), t('a3), t('a4)),
) => t('b) = "combine";

/* Test:
   let s = make(1);
   let t = map((. x) => x + 1, s); */
[@bs.send.pipe: t('a)] external map: ((. 'a) => 'b) => t('b) = "";
```

`[@bs.send.pipe: t('a)]` tells BuckleScript to inject a final parameter of type `t('a)` into the external, and generate a method call to _that_ parameter. It's very useful but was somewhat prematurely removed from the BuckleScript doc site.

**Comment by kristianmandrup** [comment]
Wow! Thank you so much :) I would never had figured that out at my current level.
Super excited. Let's see if I can transfer this knowledge to my next libs. Cheers!!

**Comment by yawaramin** [comment]
Good luck! Keep at it :-)

**Comment by kristianmandrup** [comment]
Why use the abstract type `'a` and not simply `type a;` 
If seen others use that approach. Also I see many specify types of the simple form>

```js
module Stream {
  type t;
}
```

Which is obviously "sufficient", but I'd imagine you would loose code assistance and type assurance when you are using an instance of that type?

**Comment by yawaramin** [comment]
They have slightly different uses. Normally, providing a type like `t('a)` means we allow the bindings user to decide what the concrete type will be. E.g., arrays have the generic type `array('a)` so users can have `array(string)`, `array(int)`, etc. Similarly we can have `Stream.t(int)`, `Stream.t(string)`, and so on.

About code assistance–normally we don't use values of these types in an OOP style, i.e. we don't say `stream.map(f)`, rather we say `Stream.map(f, stream)`. So the autocompletion kicks in when you write `Stream.` and it shows you the functions in that module.

**Comment by kristianmandrup** [comment]
So for Mithril stream, how would I use the phantom types concretely as a consumer?

Regarding the last part:

```js
let strm = Flyd.make();
strm.map(double).pipe(x);
```

This would be the "JS way" but using reason like syntax?? 

or would I normally use fastpipe syntax then and this form not available?
Hmmm... Much to learn

**Comment by kristianmandrup** [comment]
I have just added a [Stream.re](https://github.com/kristianmandrup/bs-mithril-stream/blob/master/src/Stream.re) using your pattern/suggestions. 

Does this look right?

**Comment by yawaramin** [comment]
So about your Flyd example, the Reason syntax would be:

```reason
let strm = Flyd.make();
strm |> Flyd.map(double) |> Flyd.pipe(x);
```

The `|>` is a normal function defined as `let (|>)(x, f) = f(x);`. So the above is equivalent to:

```reason
let strm = Flyd.make();
Flyd.pipe(Flyd.map(double, strm));
```

The advantage of using the forward-pipe is that it shows you data flowing clearly from left to right.

I haven't taken a close look at the `Stream.re` but at a glance you'll want to get rid of the `map` function on lines 30–31, because it's redundant–the one on line 37 is the correct version. For the rest of them what you can do is bind them one at a time and test them out by using them in the file itself. By looking at the BuckleScript output JS, you can see if the binding is correct.

**Comment by kristianmandrup** [comment]
Only problem is: `pipe` is not a static function in the JS lib, but an instance method on the Stream instance returned from `stream()`. There is no external `pipe`.

**Comment by yawaramin** [comment]
That's OK. The BuckleScript `[@bs.send]` and `[@bs.send.pipe]` annotations convert between Reason-style static functions and JavaScript-style method calls on instances. See https://github.com/glennsl/bucklescript-ffi-cheatsheet#bssendpipe and try the test for the `map` function I posted above (copy the test code from the comment and paste it immediately below), you'll see that the generated JS will be a method call like `s.map(function(x) { return x + 1; })`.

**Comment by kristianmandrup** [comment]
Wow! Learning so much! Thanks :) 
I'm now watching an excellent tutorial series on OCaml :) Need to get back to the foundations. Will make it much easier to grok I'm sure!

Feels like going back to school and finally learning and understanding the "real deal'.
You have an OCaml background?

OCaml video tutorial series:
https://www.youtube.com/watch?v=Eqz-xCHMLc8&list=PLea0WJq13cnCef-3KSU3qWFge9OGUlKx1&index=1

The billion dollar mistake (ie. why to switch to "OCaml lang" family or similar without null)
https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare

I'd recommend this series to anyone starting on the ReasonML journey. Nice, concise and to the point. Covers all the most foundational bases (I think)

**Comment by yawaramin** [comment]
Writing Scala in my day job, wishing I could get some OCaml in there too :-) I learned a lot from Dan Grossman's Programming Languages course: https://www.coursera.org/learn/programming-languages . Since I keep plugging it everywhere, let me link you to one of the recent plugs: https://users.scala-lang.org/t/learning-functional-programming-in-scala/3865/8?u=yawaramin (just replace 'Scala' with 'OCaml' in that post and you'll have the OCaml version of the plug :-)
